<ul class="breadcrumb">
		<li><a href="<?php print URL_HOME?>/index.php">Inicio</a> <span class="divider">/</span></li>
		<li><a href="<?php print URL_HOME?>/index.php/mgk_historiaacceso/lista">mgk_historiaacceso</a> <span class="divider">/</span></li>
		<li class="active">Formulario</li>
		</ul><div id="nav_bar">
		<a href="<?php print URL_HOME?>/index.php/mgk_historiaacceso/lista">Lista</a> |
		<a href="<?php print URL_HOME?>/index.php/mgk_historiaacceso/form">Nuevo</a>
		</div>
		
		<?php if ($this->mensaje!=""):?>
		    <div class="alert <?php print $this->css_mensaje;?>">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
		    <strong><?php print $this->tipo_mensaje;?> !</strong> <?php print $this->mensaje;?>.
		    </div>
		<?php endif;?>
		
		<div id="form_content">
		<form class="form-horizontal" name="<?php print $this->getName();?>" id="<?php print $this->getName();?>" action="" method="<?php print $this->getMethod();?>">
		<input type="hidden" id="form_name" name="form_name" value="<?php print $this->getName();?>" >
		<fieldset class="stylized"  >
		<legend>mgk_historiaacceso</legend>
		<input type="hidden" id="db_operacion" name="db_operacion" value="<?php print $this->getDb_operacion();?>" >
		

			<div class="control-group">
			<label class="control-label" for="historia_id">Historia_id *</label>
			<div class="controls">
			<input maxlength=10 type="text" name="historia_id" id="historia_id" placeholder="Historia_id" value="<?php print $this->bean->getHistoria_id();?>" style="width: 120px"  >
			</div>
			</div>
			

			<div class="control-group">
			<label class="control-label" for="usuario_id">Usuario_id *</label>
			<div class="controls">
			<input maxlength=10 type="text" name="usuario_id" id="usuario_id" placeholder="Usuario_id" value="<?php print $this->bean->getUsuario_id();?>" style="width: 120px"  >
			</div>
			</div>
			

			<div class="control-group">
			<label class="control-label" for="fecha_inicio">Fecha_inicio *</label>
			<div class="controls">
			<input maxlength=19 type="text" name="fecha_inicio" id="fecha_inicio" placeholder="Fecha_inicio" value="<?php print $this->bean->getFecha_inicio();?>" style="width: 228px"  >
			</div>
			</div>
			

			<div class="control-group">
			<label class="control-label" for="fecha_salida">Fecha_salida </label>
			<div class="controls">
			<input maxlength=19 type="text" name="fecha_salida" id="fecha_salida" placeholder="Fecha_salida" value="<?php print $this->bean->getFecha_salida();?>" style="width: 228px"  >
			</div>
			</div>
			

			<div class="control-group">
			<label class="control-label" for="direccion_id">Direccion_id *</label>
			<div class="controls">
			<input maxlength=5 type="text" name="direccion_id" id="direccion_id" placeholder="Direccion_id" value="<?php print $this->bean->getDireccion_id();?>" style="width: 60px"  >
			</div>
			</div>
			

			<div class="control-group">
			<label class="control-label" for="latitud">Latitud </label>
			<div class="controls">
			<input maxlength=6 type="text" name="latitud" id="latitud" placeholder="Latitud" value="<?php print $this->bean->getLatitud();?>" style="width: 72px"  >
			</div>
			</div>
			

			<div class="control-group">
			<label class="control-label" for="longitud">Longitud </label>
			<div class="controls">
			<input maxlength=6 type="text" name="longitud" id="longitud" placeholder="Longitud" value="<?php print $this->bean->getLongitud();?>" style="width: 72px"  >
			</div>
			</div>
			

	
	
</fieldset>
				
 <div class="control-group">
<div class="controls">
<label class="checkbox">
<dl>
		<dd> <div id="div_longitud" class="form_label_message"> * requerido </div>
		</dd>
		</dl>
</label>
<input class='btn btn-primary' type="submit" value="Enviar"/>				
<input  class='btn btn-inverse' type="reset" value="Restablecer">
</div>
</div>
	
	
</form>
</div>
